### PR TITLE
fix cards display in game dou_dizhu

### PR DESCRIPTION
**Pull request by somnuschaplet**
You forgot to subtract the offset of the Dealing action(51) when converting it, resulting in a problem with the display of the players' hand cards after the game ends.

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks. 

@rezunli96, can you take a look?

**Comment by rezunli96** [comment]
Thanks for finding this bug. You are absolutely correct!

**Comment by lanctot** [comment]
> Thanks for finding this bug. You are absolutely correct!

Thanks for responding. Do the changes in this PR fix the problem?

**Comment by lanctot** [comment]
Hi @somnuschaplet,

The playthrough tests are failing now.

Can you run the [regenerate_playthroughs.sh](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/scripts/regenerate_playthroughs.sh) and commit+push the fixed playthrough file?

**Comment by rezunli96** [comment]
> > Thanks for finding this bug. You are absolutely correct!
> 
> Thanks for responding. Do the changes in this PR fix the problem?

Yep it does.

**Comment by somnuschaplet** [comment]
> Hi @somnuschaplet,
> 
> The playthrough tests are failing now.
> 
> Can you run the [regenerate_playthroughs.sh](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/scripts/regenerate_playthroughs.sh) and commit+push the fixed playthrough file?

I met a little trouble in generating the playthrough, and It's already 2 o'clock in the middle of the night here (East Eighth District), and I think I will take a look at this tomorrow.

**Comment by lanctot** [comment]
Of course, no rush! Thanks

**Comment by somnuschaplet** [comment]
> Hi @somnuschaplet,
> 
> The playthrough tests are failing now.
> 
> Can you run the [regenerate_playthroughs.sh](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/scripts/regenerate_playthroughs.sh) and commit+push the fixed playthrough file?

Please review the latest commit.

**Comment by lanctot** [comment]
Looks good. Thanks. We will import it this coming week.

**Comment by somnuschaplet** [comment]
> Looks good. Thanks. We will import + merge it this coming week.

Great, have a nice weekend!

**Pull request merged**
