### PR TITLE
Updates to Spades

### PR DESCRIPTION
**Pull request by i-Madsen**
Now can get/set scores and set a bonus reward for winning/losing overall game to returns.

### CODE REVIEW

**Comment by lanctot** [comment]
Hi @i-Madsen, thanks for the updates!

Can you pull changes from master to merge with the changes to the master branch? I had to make some cosmetic changes to your code to adhere to the required style. (If you can keep these persistent and apply them elsewhere too, that'd be great.)

Once any conflicts are resolved, please push the merge commit.

**Comment by lanctot** [comment]
Also, note: I will soon not have access to the Internet for the next 8-10 days.. so apologies for any delays in responses.

**Comment by i-Madsen** [comment]
Ok, think I've got it all merged correctly and pushed once you get back. Let me know if I missed anything.

**Comment by lanctot** [comment]
Hi @i-Madsen, 

Ok the CI is fixed now as of  https://github.com/google-deepmind/open_spiel/pull/1250

Can you pull from master and push the merge commit?

**Comment by i-Madsen** [comment]
@lanctot Ok, should be merged now.

**Comment by lanctot** [comment]
> @lanctot Ok, should be merged now.

Ok seems there are some test failures for legitimate reasons (a function is marked void but I guess it's returning a bool?) Can you take a look and push a fix?

**Comment by i-Madsen** [comment]
@lanctot Looks like it's all passing now (not sure how I missed that before).

**Pull request merged**
